user_email: your@email.com
mail_type: FAIL
control:
  dt: 7.d0                                      # Duration of a time step (a.u. of time)
  niter: 3000                                   # Number of iterations
  threshold: 0.9999d0                           # Convergence threshold for the fidelity
  alpha0: 250.0d0                               # Constraint on the field amplitude
  ndump: 30                                     # Number of iterations between each writing of the field
  numberofpixels: 128                           # Number of pixels (pixel width = 2 / total time)