# This is CHAINS configuration file, it contains every information about the key directories needed by CHAINS to operate smoothly.
# This is a YAML file, see https://yaml.org/ for more information

# ========================================================= #
#                  Output files directories                 #
# ========================================================= #

# Define here the path towards the directories containing the needed output files of each program / calculation
# The job scripts will copy the relevant files from the job directories towards those output directories, and the crontab scripts will read the files present in those directories to launch the following step.

output_dir:
  orca: /CECI/home/ulb/cqp/niacobel/ORCA_OUT
  gaussian: /CECI/home/ulb/cqp/niacobel/GAUSSIAN_OUT
  qchem: /CECI/home/ulb/cqp/niacobel/QCHEM_SVP_OUT
  qoctra: /CECI/home/ulb/cqp/niacobel/CONTROL_q-SVP_OUT

# Define here the path towards the results directory
# A subdirectory will be created in it for each geometry file (molecule), containing all major output files from the different programs and scripts.

results_dir: /CECI/home/ulb/cqp/niacobel/RESULTS/q-SVP/

# ========================================================= #
#               Results Treatment Information               #
# ========================================================= #

# Name of the files and folders containing the results
results:
  main_dir: /CECI/home/ulb/cqp/niacobel/RESULTS/q-SVP/                # Folder where all the results of this molecule will be sent (a subfolder with the name of the molecule will be created)
  orca:
    folder_name: ORCA                               # Inside the molecule subfolder (e.g. <main_folder>/<mol_name>/<folder_name>)
  gaussian:
    folder_name: GAUSSIAN                           # Inside the molecule subfolder (e.g. <main_folder>/<mol_name>/<folder_name>)
  qchem:
    folder_name: QCHEM                              # Inside the molecule subfolder (e.g. <main_folder>/<mol_name>/<folder_name>)
  qoctra:
    folder_name: CONTROL                            # Inside the molecule subfolder (e.g. <main_folder>/<mol_name>/<folder_name>)
    fidelity: obj.res                               # Inside the projector folder (e.g. <main_folder>/<mol_name>/<folder_name>/projector<state_label>/<folder_name>)
    pulse_folder: 
      folder_name: Pulse                            # Inside the projector folder (e.g. <main_folder>/<mol_name>/<folder_name>/projector<state_label>/<folder_name>)
      guess_pulse: Pulse_init
      guess_pulse_param: Pulse_param_init
      final_pulse: Pulse_final
      final_pulse_param: Pulse_param_final
      final_pulse_heat: Pixel_heat_final
    pcp_folder:
      folder_name: PCP                              # Inside the projector folder
      pop_zero: popzero1
      pop_eigen: pop1
      pop_schrodinger: popzero_Sch1
