# This is the profile configuration file, it contains every information about the configurations of the different scripts and programs your molecule will run through.
# This is a YAML file, see https://yaml.org/ for more information

# ========================================================= #
#                    General Information                    #
# ========================================================= #

general: 
  charge: 0
  multiplicity: 1
  user_email: nicolas.iacobellis@ulb.be
  mail_type: FAIL

# ========================================================= #
#                    GAUSSIAN Information                   #
# ========================================================= #

gaussian:
  copy_files: True                                 # False if you don't want to copy the output files to their respective results directory (to proceed to the next step in CHAINS)
  benchmark: True                                  # True if you want to activate ABIN LAUNCHER's benchmarking option
  keywords:                                        # The keywords will be used "as-is" in the keyword line of the GAUSSIAN input file, be sure that GAUSSIAN knows them! (see GAUSSIAN's manual for more information)
    method: B3LYP
    basis_set: Def2TZVP
    other: Symmetry=(on,follow) IOp(2/15=4,2/16=3) # You can put multiple keywords on this line (separated by a space) | Here we enforce symmetry during the optimization (see https://www.researchgate.net/post/How-can-one-perform-a-symmetry-constrained-optimization-in-gaussian)

# ========================================================= #
#                      ORCA Information                     #
# ========================================================= #

orca:
  pre_opt: False                                   # True if you want to perform a pre-optimization using Grimme's PBEh-3c method
  copy_files: True                                 # False if you don't want to copy the output files to their respective results directory (to proceed to the next step in CHAINS)
  benchmark: True                                  # True if you want to activate ABIN LAUNCHER's benchmarking option
  keywords:                                        # The keywords will be used "as-is" in the keyword line of the ORCA input file, be sure that ORCA knows them! (see ORCA's manual for more information)
    method: B3LYP
    basis_set: def2-TZVP
    aux_basis_set: def2/J
    other: RIJCOSX                                 # You can put multiple keywords on this line (separated by a space)

# ========================================================= #
#                     Q-CHEM Information                    #
# ========================================================= #

qchem:
  copy_files: True                                 # False if you don't want to copy the output files to their respective results directory (to proceed to the next step in CHAINS)
  benchmark: True                                  # True if you want to activate ABIN LAUNCHER's benchmarking option
  keywords:                                        # The keywords will be used "as-is" in the Q-CHEM input file, be sure that Q-CHEM knows them! (see Q-CHEM's manual for more information)
    job_type: sp
    exchange: b3lyp
    basis_set: def2-svp
    scf_algorithm: diis                            # DIIS by default (GDM for restricted open-shell). If DIIS struggles in the initial iterations, use RCA_DIIS. If DIIS struggles to finally converge, use DIIS_GDM. If small HOMO-LUMO gaps and DIIS struggles, use LS_DIIS.
    max_scf_cycles: 100
    cis_n_roots: 9
    iqmol_fchk: true

# ========================================================= #
#                    QOCT-GRAD Information                  #
# ========================================================= #

# QOCT-GRAD PARAMETERS
# They will be used "as-is" in the QOCT-GRAD parameters file

qoctra:
  process: OPC                                    # Nature of the process: [OPC] Optimal control, [OPM] Optimal control with multiple constraints; [PCP] Post-control with pulse [PCL] Free post-control
  control:
    time_step: 7.d0                               # Duration of a time step (a.u. of time)
    max_iter: 3000                                # Maximum number of iterations
    threshold: 0.9999d0                           # Convergence threshold for the fidelity
  opc:
    nb_steps: 20000                               # Number of time steps
    alpha: 250.0d0                                # Constraint on the field amplitude
    write_freq: 30                                # Number of iterations between each writing of the field
  guess_pulse:
    pulse_type: SIM                               # Type de champ initial
    subpulse_type: sin                            # Type de sous-impulsion [sin], [pip] ou [gau]
    amplitude: 1.9447d-5                          # Amplitude des sous-impulsions (1.9447d-12 = 1 V/m)
    phase_change: 0.d0                            # Déphasage
    sign: 1                                       # Signe
  post_control:
    analy_freq: 1000                              # Number of steps between each analysis of the populations, phases, positions and energies

# ========================================================= #
#               Results Treatment Information               #
# ========================================================= #

# Name of the files and folders containing the results
results:
  main_dir: $CECIHOME/RESULTS                    # Folder where all the results of this molecule will be sent (a subfolder with the name of the molecule will be created)
  orca:
    dir_name: ORCA                               # Inside the molecule subfolder (e.g. <main_folder>/<mol_name>/<folder_name>)
  qchem:
    dir_name: QCHEM                              # Inside the molecule subfolder (e.g. <main_folder>/<mol_name>/<folder_name>)
  qoctra:
    dir_name: CONTROL                            # Inside the molecule subfolder (e.g. <main_folder>/<mol_name>/<folder_name>)
    fidelity: obj.res                               # Inside the projector folder (e.g. <main_folder>/<mol_name>/<folder_name>/projector<state_label>/<folder_name>)
    pulse_folder: 
      folder_name: Pulse                            # Inside the projector folder (e.g. <main_folder>/<mol_name>/<folder_name>/projector<state_label>/<folder_name>)
      guess_pulse: Pulse_init
      guess_pulse_param: Pulse_param_init
      final_pulse: Pulse_final
      final_pulse_param: Pulse_param_final
      final_pulse_heat: Pixel_heat_final
    pcp_folder:
      folder_name: PCP                              # Inside the projector folder
      pop_zero: popzero1
      pop_eigen: pop1
      pop_schrodinger: popzero_Sch1
