# ========================================================= #
#                    General Information                    #
# ========================================================= #

general: 
  user_email: nicolas.iacobellis@ulb.be
  mail_type: END,FAIL

# ========================================================= #
#                    QOCT-RA Information                    #
# ========================================================= #

# QOCT-RA PARAMETERS

qoctra:
  copy_files: True
  control:
    time_step: 5.0                                # Duration of a time step (a.u. of time)
    max_iter: 250                                 # Maximum number of iterations
    threshold: 0.999                              # Quality threshold for the fidelity
    conv_thresh: 0.0                              # Convergence threshold for the fidelity / projector
    write_freq: 20                                # Number of iterations between each writing of the field
  guess_pulse:
    amplitude: 1.0e7                              # Amplitude of the subpulses (in V/m)
    pulse_type: SIM                               # Type of starting guess pulse
    subpulse_type: sin                            # Type of subpulses ([sin], [pip] ou [gau])
    phase_change: 0.0                             # Dephasing
    sign: 1                                       # Sign
  post_control:
    analy_freq: 100                               # Number of steps between each analysis of the populations, phases, positions and energies

# Parameters to be considered for the OPC (only integers or float types values)
parameters:
  alpha:
    - 10
    - 27
    - 77
    - 215
    - 599
    - 1668
    - 4641
    - 12915
    - 35938
    - 100000
  duration: # in ps
    - 3
    - 6
    - 9
    - 12
    - 15
    - 18
    - 21
    - 24
    - 27
    - 30
