# ========================================================= #
#                    General Information                    #
# ========================================================= #

general: 
  user_email: nicolas.iacobellis@ulb.be
  mail_type: FAIL

# ========================================================= #
#                    QOCT-RA Information                    #
# ========================================================= #

# QOCT-RA PARAMETERS
# They will be used "as-is" in the QOCT-RA parameters file

qoctra:
  process: OPC                                    # Nature of the process: [OPC] Optimal control, [OPM] Optimal control with multiple constraints; [PCP] Post-control with pulse [PCL] Free post-control
  control:
    time_step: 0.41d0                             # Duration of a time step (a.u. of time)
    max_iter: 3000                                # Maximum number of iterations
    threshold: 0.9999d0                           # Convergence threshold for the fidelity
  opc:
    nb_steps: 10000                               # Number of time steps
    alpha: 250.0d0                                # Constraint on the field amplitude
    write_freq: 30                                # Number of iterations between each writing of the field
  guess_pulse:
    pulse_type: SIM                               # Type of starting guess pulse
    subpulse_type: gau                            # Type of subpulses ([sin], [pip] ou [gau])
    tbp: 0.44                                     # Time-bandwidth product of the pulse (Gaussian = 0.44)
    amplitude: 1.9447d-5                          # Amplitude of the subpulses (in atomic units, 1.9447d-12 u.a. = 1 V/m)
    phase_change: 0.d0                            # Dephasing
    sign: 1                                       # Sign
  post_control:
    analy_freq: 1000                              # Number of steps between each analysis of the populations, phases, positions and energies