# ========================================================= #
#                    General Information                    #
# ========================================================= #

general: 
  user_email: nicolas.iacobellis@ulb.be
  mail_type: FAIL

# ========================================================= #
#                    QOCT-RA Information                    #
# ========================================================= #

# QOCT-RA PARAMETERS
# They will be used "as-is" in the QOCT-RA parameters file

qoctra:
  process: OPC                                    # Nature of the process: [OPC] Optimal control, [OPM] Optimal control with multiple constraints; [PCP] Post-control with pulse [PCL] Free post-control
  control:
    time_step: 3.0d0                              # Duration of a time step (a.u. of time)
    max_iter: 2500                                # Maximum number of iterations
    threshold: 0.9999d0                           # Convergence threshold for the fidelity
  opc:
    write_freq: 1                                 # Number of iterations between each writing of the field
    bandwidth: 147.1                              # Spectral bandwidth of the pulse, in cm-1 (duration_FWHM = 100 fs => bandwidth_FWHM ~= 147.1 cm-1)
    amplitude_filter: True                        # True if you want to limit the maximum amplitude of the pulse (derived from the ionization potential of the molecule), default is False
    spectral_filter: True                         # True if you want to limit the spectral bandwidth of the pulse, default is False
    max_fluence: True                             # True if you want to limit the maximum fluence of the pulse, default is False
  guess_pulse:
    pulse_type: SIM                               # Type of starting guess pulse
    subpulse_type: sin                            # Type of subpulses ([sin], [pip] ou [gau])
    phase_change: 0.d0                            # Dephasing
    sign: 1                                       # Sign
  post_control:
    analy_freq: 100                               # Number of steps between each analysis of the populations, phases, positions and energies
