# ========================================================= #
#                    General Information                    #
# ========================================================= #

general: 
  charge: 0
  multiplicity: 1
  user_email: nicolas.iacobellis@ulb.be
  mail_type: FAIL

# ========================================================= #
#                      ORCA Information                     #
# ========================================================= #

orca:
  pre_opt: False                                   # True if you want to perform a pre-optimization using Grimme's PBEh-3c method
  copy_files: True                                 # False if you don't want to copy the output files to their respective results directory (to proceed to the next step in CHAINS)
  benchmark: True                                  # True if you want to activate ABIN LAUNCHER's benchmarking option
  keywords:                                        # The keywords will be used "as-is" in the keyword line of the ORCA input file, be sure that ORCA knows them! (see ORCA's manual for more information)
    method: B3LYP
    basis_set: def2-TZVP
    aux_basis_set: def2/J
    other: RIJCOSX                                 # You can put multiple keywords on this line (separated by a space)
