# ========================================================= #
#                    General Information                    #
# ========================================================= #

general: 
  charge: 0
  multiplicity: 1
  user_email: nicolas.iacobellis@ulb.be
  mail_type: FAIL

# ========================================================= #
#                     Q-CHEM Information                    #
# ========================================================= #

qchem:
  copy_files: True                                 # False if you don't want to copy the output files to their respective results directory (to proceed to the next step in CHAINS)
  benchmark: True                                  # True if you want to activate ABIN LAUNCHER's benchmarking option
  keywords:                                        # The keywords will be used "as-is" in the Q-CHEM input file, be sure that Q-CHEM knows them! (see Q-CHEM's manual for more information)
    job_type: sp
    exchange: b3lyp
    basis_set: def2-tzvp
    scf_algorithm: diis                            # DIIS by default (GDM for restricted open-shell). If DIIS struggles in the initial iterations, use RCA_DIIS. If DIIS struggles to finally converge, use DIIS_GDM. If small HOMO-LUMO gaps and DIIS struggles, use LS_DIIS.
    max_scf_cycles: 100
    cis_n_roots: 6
    iqmol_fchk: true
